// Generated by gencpp from file ros_arduino_base/UpdateGains.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_BASE_MESSAGE_UPDATEGAINS_H
#define ROS_ARDUINO_BASE_MESSAGE_UPDATEGAINS_H

#include <ros/service_traits.h>


#include <ros_arduino_base/UpdateGainsRequest.h>
#include <ros_arduino_base/UpdateGainsResponse.h>


namespace ros_arduino_base
{

struct UpdateGains
{

typedef UpdateGainsRequest Request;
typedef UpdateGainsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateGains
} // namespace ros_arduino_base


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_base::UpdateGains > {
  static const char* value()
  {
    return "8228f4ec4b23c46622122a1e302577ff";
  }

  static const char* value(const ::ros_arduino_base::UpdateGains&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_base::UpdateGains > {
  static const char* value()
  {
    return "ros_arduino_base/UpdateGains";
  }

  static const char* value(const ::ros_arduino_base::UpdateGains&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_base::UpdateGainsRequest> should match 
// service_traits::MD5Sum< ::ros_arduino_base::UpdateGains > 
template<>
struct MD5Sum< ::ros_arduino_base::UpdateGainsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_base::UpdateGains >::value();
  }
  static const char* value(const ::ros_arduino_base::UpdateGainsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_base::UpdateGainsRequest> should match 
// service_traits::DataType< ::ros_arduino_base::UpdateGains > 
template<>
struct DataType< ::ros_arduino_base::UpdateGainsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_base::UpdateGains >::value();
  }
  static const char* value(const ::ros_arduino_base::UpdateGainsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_base::UpdateGainsResponse> should match 
// service_traits::MD5Sum< ::ros_arduino_base::UpdateGains > 
template<>
struct MD5Sum< ::ros_arduino_base::UpdateGainsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_base::UpdateGains >::value();
  }
  static const char* value(const ::ros_arduino_base::UpdateGainsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_base::UpdateGainsResponse> should match 
// service_traits::DataType< ::ros_arduino_base::UpdateGains > 
template<>
struct DataType< ::ros_arduino_base::UpdateGainsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_base::UpdateGains >::value();
  }
  static const char* value(const ::ros_arduino_base::UpdateGainsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_BASE_MESSAGE_UPDATEGAINS_H
