// Generated by gencpp from file ros_arduino_msgs/CmdDiffVel.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_CMDDIFFVEL_H
#define ROS_ARDUINO_MSGS_MESSAGE_CMDDIFFVEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_arduino_msgs
{
template <class ContainerAllocator>
struct CmdDiffVel_
{
  typedef CmdDiffVel_<ContainerAllocator> Type;

  CmdDiffVel_()
    : left(0.0)
    , right(0.0)  {
    }
  CmdDiffVel_(const ContainerAllocator& _alloc)
    : left(0.0)
    , right(0.0)  {
    }



   typedef float _left_type;
  _left_type left;

   typedef float _right_type;
  _right_type right;




  typedef boost::shared_ptr< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> const> ConstPtr;

}; // struct CmdDiffVel_

typedef ::ros_arduino_msgs::CmdDiffVel_<std::allocator<void> > CmdDiffVel;

typedef boost::shared_ptr< ::ros_arduino_msgs::CmdDiffVel > CmdDiffVelPtr;
typedef boost::shared_ptr< ::ros_arduino_msgs::CmdDiffVel const> CmdDiffVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_arduino_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ros_arduino_msgs': ['/home/designer/catkin_ws/src/ros_arduino/ros_arduino_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a927990ab5d5c3d628e2d52b8533e52";
  }

  static const char* value(const ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a927990ab5d5c3dULL;
  static const uint64_t static_value2 = 0x628e2d52b8533e52ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_arduino_msgs/CmdDiffVel";
  }

  static const char* value(const ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left\n\
float32 right\n\
";
  }

  static const char* value(const ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CmdDiffVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_arduino_msgs::CmdDiffVel_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_CMDDIFFVEL_H
